# Generated by Django 4.2.16 on 2024-11-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_avatar_alter_answer_user_questionlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='for_question',
        ),
    ]
